import React from 'react';
import { ShieldCheck, Mic, FileAudio, Brain, ArrowRight, Users, CheckCircle2, Zap } from 'lucide-react';
import { Button } from '../components/common/Button';
import { Card } from '../components/common/Card';

const STEPS = [
  {
    num: '01',
    icon: FileAudio,
    title: 'Upload a Call Recording',
    desc: 'Upload the suspicious call you received as an audio file. Supported formats include MP3, WAV, M4A, OGG, and FLAC. The file should contain audible speech.',
    detail: 'Optionally, also upload a reference voice — a known recording of the person you expected to be on the call. This enables speaker comparison.',
  },
  {
    num: '02',
    icon: Mic,
    title: 'Voice Authenticity Analysis',
    desc: 'EchoForge analyzes the acoustic properties of the voice — including pitch coherence, spectral patterns, and phase artifacts — to detect signs of AI voice synthesis.',
    detail: 'This check identifies whether a voice was likely generated by an AI voice cloning system or recorded naturally.',
  },
  {
    num: '03',
    icon: Users,
    title: 'Speaker Comparison',
    desc: 'If a reference voice is provided, EchoForge compares the vocal characteristics of the suspicious recording against the reference to assess speaker identity.',
    detail: 'If no reference is provided, this step is skipped and the result will note that speaker comparison was unavailable.',
  },
  {
    num: '04',
    icon: Brain,
    title: 'Conversation Risk Analysis',
    desc: 'EchoForge analyzes the content of the conversation — scanning for urgency language, financial pressure tactics, impersonation patterns, and suspicious requests.',
    detail: 'This layer helps identify calls that may not use cloned voices but still follow known scam conversation scripts.',
  },
  {
    num: '05',
    icon: ShieldCheck,
    title: 'Risk Assessment',
    desc: 'All three signals are combined into a final risk score and verdict: LOW RISK, HIGH RISK, or UNCERTAIN RESULT.',
    detail: 'Each signal is weighted according to reliability, and confidence levels are factored into the final assessment.',
  },
  {
    num: '06',
    icon: CheckCircle2,
    title: 'Safety Guidance',
    desc: 'You receive plain-language safety advice tailored to the verdict — what to do, what to avoid, and when to seek further verification.',
    detail: 'EchoForge provides actionable guidance, not just a score. Understanding why a call was flagged is as important as the result itself.',
  },
];

export function HowItWorksPage({ onNavigateTo }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '4rem' }}>
      {/* Header */}
      <section>
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', background: 'var(--soft-blue)', color: 'var(--primary)', padding: '0.35rem 1rem', borderRadius: '9999px', fontSize: '0.82rem', fontWeight: 800, marginBottom: '1.25rem' }}>
          <ShieldCheck size={14} />
          <span>How It Works</span>
        </div>
        <h1 style={{ fontSize: 'clamp(2rem, 4.5vw, 3.2rem)', marginBottom: '0.75rem' }}>
          From suspicious call to clear safety verdict
        </h1>
        <p style={{ fontSize: '1.05rem', color: 'var(--text-secondary)', maxWidth: '580px', lineHeight: 1.65 }}>
          EchoForge runs three independent layers of analysis on your uploaded recording, combining all signals into a single, understandable safety assessment.
        </p>
      </section>

      {/* Three Layers Overview */}
      <section>
        <div className="section-heading-center" style={{ marginBottom: '1.75rem' }}>
          <h2>Three independent layers of analysis</h2>
          <p>Each layer evaluates the call from a different angle. All three combine for the final verdict.</p>
        </div>

        <div className="journey-cards-flow">
          <div className="journey-step-card" style={{ textAlign: 'center' }}>
            <Mic size={32} style={{ color: 'var(--primary)', margin: '0 auto 0.75rem' }} />
            <span className="journey-step-num" style={{ margin: '0 auto 0.5rem' }}>Layer 01</span>
            <h4 className="journey-step-title">Voice Authenticity</h4>
            <p className="journey-step-desc">Detects whether the voice is AI-generated or synthetic.</p>
          </div>

          <div className="journey-flow-arrow"><ArrowRight size={22} /></div>

          <div className="journey-step-card" style={{ textAlign: 'center' }}>
            <Users size={32} style={{ color: 'var(--primary)', margin: '0 auto 0.75rem' }} />
            <span className="journey-step-num" style={{ margin: '0 auto 0.5rem' }}>Layer 02</span>
            <h4 className="journey-step-title">Speaker Comparison</h4>
            <p className="journey-step-desc">Checks if the caller matches the expected speaker.</p>
          </div>

          <div className="journey-flow-arrow"><ArrowRight size={22} /></div>

          <div className="journey-step-card" style={{ textAlign: 'center' }}>
            <Brain size={32} style={{ color: 'var(--primary)', margin: '0 auto 0.75rem' }} />
            <span className="journey-step-num" style={{ margin: '0 auto 0.5rem' }}>Layer 03</span>
            <h4 className="journey-step-title">Conversation Risk</h4>
            <p className="journey-step-desc">Identifies scam language, urgency, and suspicious patterns.</p>
          </div>
        </div>
      </section>

      {/* Step-by-step detail */}
      <section className="how-it-works-section">
        <div className="section-heading-center">
          <h2>Step-by-step breakdown</h2>
          <p>Here's exactly what happens when you upload a call to EchoForge.</p>
        </div>

        <div className="how-it-works-steps">
          {STEPS.map((step) => (
            <div key={step.num} className="how-step-row">
              <div className="how-step-icon-col">
                <div className="how-step-circle">{step.num}</div>
              </div>
              <div className="how-step-body">
                <div className="how-step-title">{step.title}</div>
                <div className="how-step-desc">{step.desc}</div>
                <div style={{ fontSize: '0.86rem', color: 'var(--text-muted)', marginTop: '0.35rem', fontStyle: 'italic' }}>
                  {step.detail}
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Understanding Results Note */}
      <Card style={{ background: 'var(--soft-blue)', border: '1px solid rgba(15,76,92,0.15)' }}>
        <h2 style={{ fontSize: '1.4rem', marginBottom: '0.75rem' }}>Understanding the verdict</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
          {[
            { label: 'LOW RISK', color: 'var(--success)', bg: 'var(--success-light)', desc: 'No significant risk signals detected. Still use your judgment.' },
            { label: 'HIGH RISK', color: 'var(--danger)', bg: 'var(--danger-light)', desc: 'Significant risk signals found. Do not share sensitive information.' },
            { label: 'UNCERTAIN', color: 'var(--warning)', bg: 'var(--warning-light)', desc: 'Signals were mixed or insufficient. Treat the call with caution.' },
          ].map(({ label, color, bg, desc }) => (
            <div key={label} style={{ display: 'flex', alignItems: 'center', gap: '1rem', background: bg, borderRadius: '12px', padding: '0.85rem 1rem', border: `1px solid ${color}30` }}>
              <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.78rem', fontWeight: 800, color, minWidth: '90px', letterSpacing: '0.04em' }}>{label}</span>
              <span style={{ fontSize: '0.9rem', color: 'var(--text-primary)' }}>{desc}</span>
            </div>
          ))}
        </div>
        <p style={{ fontSize: '0.87rem', color: 'var(--text-muted)', marginTop: '1rem', fontStyle: 'italic' }}>
          EchoForge provides assessments, not guarantees. Always verify important requests independently.
        </p>
      </Card>

      {/* CTA */}
      <div style={{ textAlign: 'center' }}>
        <h2 style={{ marginBottom: '0.5rem' }}>Ready to analyze a call?</h2>
        <p style={{ color: 'var(--text-secondary)', marginBottom: '1.5rem' }}>
          Upload a suspicious recording and let EchoForge do the analysis.
        </p>
        <Button variant="primary" size="lg" onClick={() => onNavigateTo?.('analyze-call')} icon={Zap}>
          Analyze a Call Recording
        </Button>
      </div>
    </div>
  );
}
