Add-Type -AssemblyName System.Speech
$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
$synth.SetOutputToWaveFile("audio/synthetic_tts_1.wav")
$synth.Speak("This is a synthetic audio test recording generated by a text to speech system for testing AI voice detection in EchoForge.")
$synth.SetOutputToWaveFile("audio/synthetic_tts_2.wav")
$synth.Speak("Synthetic speech models and neural vocoders often leave subtle spectral artifacts that machine learning detectors can identify.")
$synth.SetOutputToWaveFile("audio/synthetic_tts_3.wav")
$synth.Speak("Cybersecurity systems require reliable voice authenticity screening to prevent social engineering and fraudulent calls.")
$synth.Dispose()
Write-Host "TTS generation complete."
